var studentname = "hassaan";
var studentname2 = "laiba";
var studentage = 20;
var student2age = 23;
console.log("is student name is Hassaan , i predict True");
console.log(studentname == "hassaan");
console.log("is student name is wasay i predict false");
console.log(studentname == "wasay");
console.log("is student name is laiba i predict true");
console.log(studentname2 == "laiba");
console.log("is student name is zoya i predict false");
console.log(studentname == "zoya");
console.log("is student name is shahid i predict false");
console.log(studentname == "shahid");
console.log("is student one age is 20 , i predict true");
console.log(studentage == 20);
console.log("is student two age is 20 , i predict true");
console.log(student2age == 20);
console.log("is student two age is 21 , i predict false");
console.log(student2age == 21);
console.log("is student two age is 23 , i predict true");
console.log(student2age == 23);
console.log("is student one age is 20 , i predict false");
console.log(studentage == 20);
